default_platform :ios

desc 'Release new pod version'

cocoaSource = "https://github.com/CocoaPods/Specs.git"

lane :git_tag do |options|

  target_project = options[:project]
  target_version = options[:version]
  spec_path = "#{target_project}.podspec"
  
  git_pull
  ensure_git_branch
  version_bump_podspec(path: spec_path, version_number: target_version)

  git_add(path: '.')
  git_commit(path: '.', message: 'release')
  push_to_git_remote
  if git_tag_exists(tag: target_version)
      UI.message("Tag #{target_version} already exists, then, delete it! 💥")
      remove_git_tag(tag: target_version)
  end

  add_git_tag(tag: target_version)
  push_git_tags
end

lane :pod_repo_push do |options|

  target_repo    = options[:repo]
  target_project = options[:project]
  target_version = options[:version]
  target_source = options[:source]
  spec_path = "#{target_project}.podspec"

  git_tag()
  UI.message("👉 Start release lib #{target_project} new version #{target_version}")
  pod_push(path: spec_path, repo: target_repo, sources: [target_source, cocoaSource], allow_warnings: true)
end

lane :pod_repo_push_use_libraries do |options|
  
  target_repo    = options[:repo]
  target_project = options[:project]
  target_version = options[:version]
  target_source = options[:source]
  spec_path = "#{target_project}.podspec"
  
  git_tag
  UI.message("👉 Start release lib #{target_project} new version #{target_version}")
  pod_push(path: spec_path, repo: target_repo, sources: [target_source, cocoaSource], use_libraries: true, allow_warnings: true)
end
